version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "area/dependencies"
    groups: # group minor/patch updates together
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "area/dependencies"
    groups: # group minor/patch updates together
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
